version: '3'
name: 2048-game
services:
  db:
    build: ./db
    volumes:
      - 2048GameDB:/var/lib/mysql
    ports:
      - '82:3306'
  php:
    build: .
    ports:
      - '8001:80'
volumes: 
  2048GameDB: